### PR TITLE
test adding thanks

### PR DESCRIPTION
**Pull request by TyDunn**

### CODE REVIEW

**Comment by TyDunn** [comment]
@erohmensing I think you are right. If you just fork the repo, it somehow creates a PR on the rasahq repo?

**Comment by erohmensing** [comment]
what do you mean by "fork just the repo"?

**Comment by TyDunn** [comment]
@erohmensing If I click the `Fork` button in the top right. I get my own copy of the repo, which I can add a deploy key to and connect to Integrated Version Control. But then when I push changes in Rasa X, it pushes them to this repo 🤔

**Comment by erohmensing** [comment]
Ah, really weird 🤔

**Comment by erohmensing** [comment]
Maybe that is an issue in the code where it's hardcoded as origin or something

**Comment by TyDunn** [comment]
@wochinge Any ideas? I also happened to one of the Rasa Certification Workshop attendees: https://github.com/RasaHQ/financial-demo/pull/14

**Comment by wochinge** [comment]
@TyDunn Which URL did you add to Rasa X then?

**Comment by TyDunn** [comment]
@wochinge My forked repo. I can't even add a deploy key to this repo because I don't have permissions

**Comment by wochinge** [comment]
I think this is GitHub when you create the branch. It by default selects the original repository as target

**Comment by wochinge** [comment]
happened to me last week, too 😆  https://github.com/facebook/duckling/pull/471

**Comment by erohmensing** [comment]
Yeah it happened to me as well recently, i think it's just a miscommunication 😄bc now that i think of this i've gotten it to work fine for our test rasa x on my fork of rasa-demo

**Comment by TyDunn** [comment]
I figured. I am sort of thinking we just instruct people to clone, rather than fork

**Pull request closed without merging**
