### PR TITLE
Rasa x may 29th 20  12 00 18 am 9e2e1850 a12e 11ea 821d f94ba030b974

### PR DESCRIPTION
**Pull request by ig-shaun**

### CODE REVIEW

**Comment by sara-tagger** [comment]
Thanks for submitting a pull request 🚀 @dakshvar22 will take a look at it as soon as possible ✨

**Comment by dakshvar22** [comment]
@ig-shaun I assume this was opened by mistake?

**Comment by melindaloubser1** [comment]
Hi @ig-shaun ! Just checking, did you intend to open this PR onto this repo, or your fork of the repo?

**Comment by ig-shaun** [comment]
Sorry, my mistake - it was for our fork!
PS have messaged you Melinda as we are super stuck & frustrated with the ongoing problem of RasaX not training as it says nothing has changed. I posted on the forum, but have not received any advice on how to continue. Any advice & help would be much appreciated!

**Comment by melindaloubser1** [comment]
No problem, I'll close it then. Can you post the link of the forum post in question?

**Pull request closed without merging**
