### PR TITLE
Convert

### PR DESCRIPTION
**Pull request by amn41**

### CODE REVIEW

**Comment by amn41** [comment]
wdyt @akelad & @melindaloubser1 ? Not sure if we should merge this, maybe just in a branch for eval from the CDD hackathon? Including both convert & spacy in this starter pack seems a bit heavy. ( have taken spaCy out in this PR for the purpose of testing)

**Comment by melindaloubser1** [comment]
Ja I think originally we removed convert because of the heaviness - On the other hand, maybe it's good if one starter pack uses it.

**Comment by akelad** [comment]
what were the original results like? we def need spacy in :D

**Comment by amn41** [comment]
see here: https://github.com/RasaHQ/financial-demo/pull/71#issuecomment-672928364 

so weighted average intent f1 goes from 0.86 to 0.96 (!) 

entities not really affected

**Comment by melindaloubser1** [comment]
put spacy back so we can see how long eval takes. Isn't it also a thing that windows users can't use convert right now because of `tensorflow_text`? That would be a reason not to do it.

**Comment by melindaloubser1** [comment]
Looks like it's a matter of ~4 min vs ~5 min; the only reason I'd say not to do this is if it prevents windows users from using the starterpack as is (tensorflow-text requirement)

**Comment by amn41** [comment]
I think when we switch to tf2.3 that won't be a problem anymore? but not sure

**Comment by akelad** [comment]
yeah let's wait until this is compatible for windows users as well

**Comment by indam23** [comment]
closing since Convert is no longer a publicly available model

**Pull request closed without merging**
