### PR TITLE
Rasa 2 0

### PR DESCRIPTION
**Pull request by ArjaanBuijk**
Migrated bot to rasa 2.0, and extended with following capabilities:

- Asks user to continue when slot validation fails repeatedly. It does this for every slot of every form, but some slot have an actual `explain_{slot}` method to give a more detailed message.
- Switching is possible between all of the forms, at any time.
- User will be asked to confirm they want to switch
- Once next form is done, user will be asked if they want to switch back
- User can ask for `show balance`, `show recipients` & `show transfer charge` at any time. If user asks while a form is active, they will be asked to confirm if they want to continue with the form.

This example conversation demonstrates the form switching and asking of questions:
image

This example conversation demonstrates a repeated slot validation failure for a slot with an `explain_{slot}` method:
image

### CODE REVIEW

**Comment by b-quachtran** [comment]
@ArjaanBuijk For context switching, it looks like you're handling it directly within the FormAction using the `shared_validate_continue_form` & respective validate methods, which seems like quite a bit of added complexity in the actions code. 

For Sara 2.0, I've implemented context-switching entirely using [rules](https://github.com/RasaHQ/rasa-demo/blob/rasa-2.0/data/rules/forms.yml#L44) and [stories](https://github.com/RasaHQ/rasa-demo/blob/rasa-2.0/data/stories/closetheloop.yml#L164), so I'm curious to get your take on this since we should probably keep it consistent across the demo bots.

**Comment by ArjaanBuijk** [comment]
@b-quachtran ,
The context switching is fully handled with stories, very similar to Sara 2.0.

The `shared_validate_continue_form` is used to handle repeated slot validation failures. If slot validation fails repeatedly, the bot will ask the user if they want to continue witth the form. Additionally, it will explain the slot if an `explain_{slot}` method is provided.

**Comment by b-quachtran** [comment]
> @b-quachtran ,
> The context switching is fully handled with stories, very similar to Sara 2.0.
> 
> The `shared_validate_continue_form` is used to handle repeated slot validation failures. If slot validation fails repeatedly, the bot will ask the user if they want to continue witth the form. Additionally, it will explain the slot if an `explain_{slot}` method is provided.
> 
> A separate note. When migrating financial-demo, I went through all the stories of the rasa 1.0 version, and if a story was fully handled by rules, I removed the story from the training data, but added it as a test_story. For Sara 2.0, it seems the stories were just migrated over. For example, [this story](https://github.com/RasaHQ/rasa-demo/blob/c20015b0289df487f0f89e1bee4c63e2b505e443/data/stories/closetheloop.yml#L185) is not needed anymore, it is fully handled by rules. Was that indeed the approach?

With Sara, failed slot validations is handled with rules instead of in the form code so that's where I think we need some consistency. 

On story migration, I removed the majority of stories that were covered by rules but left in a few of the longer interaction stories to serve as examples. They can be removed pretty easily since I only left in a handful of them.

**Review by b-quachtran — APPROVED** [review]

**Comment by akelad** [comment]
can this be merged at this point?

**Comment by ArjaanBuijk** [comment]
> can this be merged at this point?

@akelad ,
not yet. The Udemy course has not yet been switched over.

**Comment by ArjaanBuijk** [comment]
Merged manually from command line.

**Pull request merged**
